name: Build documentation

on:
  push:
    branches:
      - main
      - doc-builder*
      - v*-release

jobs:
  build_and_package:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - uses: actions/checkout@v2
        with:
          repository: 'huggingface/doc-builder'
          path: doc-builder

      - uses: actions/checkout@v2
        with:
          repository: 'huggingface/doc-build'
          path: doc-build
          token: ${{ secrets.HUGGINGFACE_PUSH }}
      
      - uses: actions/checkout@v2
        with:
          repository: 'huggingface/accelerate'
          path: accelerate
      
      - name: Loading cache.
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/.cache/pip
          key: v1-test_build_doc
          restore-keys: |
            v1-test_build_doc-${{ hashFiles('setup.py') }}
            v1-test_build_doc

      - name: Setup environment
        run: |
          pip install git+https://github.com/huggingface/doc-builder
          cd accelerate
          pip install .[quality]
          cd ..

      - name: Setup git
        run: |
          git config --global user.name "Hugging Face Doc Builder"
          git config --global user.email docs@huggingface.co
          
      - name: Create build directory
        run: |
          cd doc-build
          git pull
          cd ..
          mkdir build_dir
          mkdir build_dir/accelerate
          cp doc-build/accelerate/_versions.yml build_dir/accelerate

      - name: Make documentation
        run: |
          cd doc-builder &&
          doc-builder build accelerate ../accelerate/docs/source --build_dir ../doc-build --clean --html &&
          cd ..
        env:
          NODE_OPTIONS: --max-old-space-size=6656

      - name: Push to repositories
        run: |
          cd doc-build
          git pull
          mv ../build_dir/accelerate/_versions.yml accelerate/
          rm -rf accelerate/$(ls ../build_dir/accelerate)
          mv ../build_dir/accelerate/$(ls ../build_dir/accelerate) accelerate/$(ls ../build_dir/accelerate)
          git status

          if [[ `git status --porcelain` ]]; then 
            git add .
            git commit -m "Updated with commit ${{ github.sha }} \n\nSee: https://github.com/huggingface/accelerate/commit/${{ github.sha }}"
            git push origin main
          else
            echo "No diff in the documentation."
          fi

          cd ..
